trigger: none
pr: none

variables:
- group: azdevopsterraform

stages:
  - stage: BuildCoreInfraPOC
    jobs:
      - job: BuildNSGandPublish
        pool: terraformpool
        continueOnError: false
        steps:
        - task: InstallSSHKey@0
          inputs:
            knownHostsEntry: '$(ssh_known_hosts)'
            sshPublicKey: '$(myPubKey)'
            sshKeySecureFile: 'id_rsa'
            
        - task: CmdLine@2
          displayName: terraform init
          inputs:
            script: |
              echo Running Terrafrom Init
              az login --identity &&
              terraform init && terraform validate
            workingDirectory: '$(System.DefaultWorkingDirectory)/NSG/poc'
            
        - task: CmdLine@2
          displayName: terraform plan
          inputs:
            script: |
              echo Running Terrafrom Plan 
              terraform plan -out="out.plan" -input=false
            workingDirectory: '$(System.DefaultWorkingDirectory)/NSG/poc'
            
        - task: CopyFiles@2
          inputs:
            Contents: 'NSG/poc/*'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'

        - task: PublishPipelineArtifact@1
          displayName: 'Publish Plan Artifact'
          inputs:
            targetPath: '$(Build.ArtifactStagingDirectory)'
            artifactName: 'nsgpocplan'

      - job: BuildvNetAndPublish
        dependsOn: BuildNSGandPublish
        pool: terraformpool
        continueOnError: false
        steps:
        - task: InstallSSHKey@0
          inputs:
            knownHostsEntry: '$(ssh_known_hosts)'
            sshPublicKey: '$(myPubKey)'
            sshKeySecureFile: 'id_rsa'
            
        - task: CmdLine@2
          displayName: terraform init
          inputs:
            script: |
              echo Running Terrafrom Init
              az login --identity &&
              terraform init && terraform validate
            workingDirectory: '$(System.DefaultWorkingDirectory)/vnet/poc'
            
        - task: CmdLine@2
          displayName: terraform plan
          inputs:
            script: |
              echo Running Terrafrom Plan 
              terraform plan -out="out.plan" -input=false
            workingDirectory: '$(System.DefaultWorkingDirectory)/vnet/poc'
            
        - task: CopyFiles@2
          inputs:
            Contents: 'vnet/poc/*'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'

        - task: PublishPipelineArtifact@1
          displayName: 'Publish Plan Artifact'
          inputs:
            targetPath: '$(Build.ArtifactStagingDirectory)'
            artifactName: 'vNetpocplan'
          
      - job: BuildKeyVaultAndPublish
        pool: terraformpool
        continueOnError: false
        dependsOn: BuildvNetAndPublish
        steps:
        - task: InstallSSHKey@0
          inputs:
            knownHostsEntry: '$(ssh_known_hosts)'
            sshPublicKey: '$(myPubKey)'
            sshKeySecureFile: 'id_rsa'
            
        - task: CmdLine@2
          displayName: terraform init
          inputs:
            script: |
              echo Running Terrafrom Init
              az login --identity &&
              terraform init && terraform validate
            workingDirectory: '$(System.DefaultWorkingDirectory)/keyVault/poc'
            
        - task: CmdLine@2
          displayName: terraform plan
          inputs:
            script: |
              echo Running Terrafrom Plan 
              terraform plan -out="out.plan" -input=false
            workingDirectory: '$(System.DefaultWorkingDirectory)/keyVault/poc'
            
        - task: CopyFiles@2
          inputs:
            Contents: 'keyVault/poc/*'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'

        - task: PublishPipelineArtifact@1
          displayName: 'Publish Plan Artifact'
          inputs:
            targetPath: '$(Build.ArtifactStagingDirectory)'
            artifactName: 'KeyVaultpocplan'

  - stage: DeployCoreInfraPOC
    dependsOn: BuildCoreInfraPOC
    jobs:
    - deployment: DeployAndApplyTerraform
      environment: POC
      pool: terraformpool
        # vmImage: ubuntu-latest
      strategy:
        runOnce:
          deploy:
            steps:
            - task: InstallSSHKey@0
              inputs:
                knownHostsEntry: '$(ssh_known_hosts)'
                sshPublicKey: '$(myPubKey)'
                sshKeySecureFile: 'id_rsa'
            - task: CmdLine@2
              displayName: terraform apply NSG
              inputs:
                script: |
                  echo Running Terrafrom Apply 
                  terraform init && terraform apply "out.plan"
                workingDirectory: '$(Pipeline.Workspace)/nsgpocplan/NSG/poc'

            - task: CmdLine@2
              displayName: terraform apply VNET
              inputs:
                script: |
                  echo Running Terrafrom Apply 
                  terraform init && terraform apply "out.plan"
                workingDirectory: '$(Pipeline.Workspace)/vNetpocplan/vnet/poc'
            - task: CmdLine@2
              displayName: terraform apply KeyVault
              inputs:
                script: |
                  echo Running Terrafrom Apply 
                  terraform init && terraform apply "out.plan"
                workingDirectory: '$(Pipeline.Workspace)/KeyVaultpocplan/keyVault/poc'